
trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_stage
  displayName: Build React
  jobs: BuildStage
  -job: Build stage
  
steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'

# steps:
# - task: Npm@1
#   inputs:
#     command: 'install'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     workingDir: '$(Build.SourcesDirectory)'
#     customCommand: 'npm run build'

steps:   
     - task: CmdLine@2
       inputs:
         script: |
           npm install
           npm run build
  
